# Generated by Django 4.0.2 on 2022-10-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discotecas',
            old_name='id',
            new_name='discotecaId',
        ),
    ]
