# Generated by Django 4.0.2 on 2023-01-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0002_rename_id_discotecas_discotecaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Nombre')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto')),
                ('edad', models.IntegerField(verbose_name='edad')),
                ('dni', models.CharField(max_length=9, verbose_name='dni')),
                ('correo', models.CharField(max_length=100, verbose_name='correo')),
                ('admin', models.IntegerField(verbose_name='admin')),
            ],
        ),
    ]
