# Generated by Django 4.0.2 on 2023-01-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0003_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(default='', max_length=100, verbose_name='contraseña'),
        ),
    ]
