# Generated by Django 4.0.2 on 2023-01-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0004_usuarios_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='admin',
            field=models.IntegerField(null=True, verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='apellidos',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto de Perfil'),
        ),
    ]
