# Generated by Django 4.0.2 on 2023-01-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0005_alter_usuarios_admin_alter_usuarios_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='usuario',
            field=models.CharField(default='', max_length=100, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.CharField(max_length=9, unique=True, verbose_name='dni'),
        ),
    ]
