# Generated by Django 4.0.2 on 2023-01-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0006_remove_usuarios_apellidos_remove_usuarios_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discotecass',
            fields=[
                ('discotecaId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto de Perfil')),
                ('direccion', models.CharField(max_length=500, verbose_name='direccion')),
                ('descripcion', models.CharField(max_length=1500, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Fiestas',
            fields=[
                ('fiestaId', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto de Perfil')),
                ('descripcion', models.CharField(max_length=1500, verbose_name='descripcion')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('personas_reservado', models.IntegerField(verbose_name='Personas maxima del reservado')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('numero_entradas', models.IntegerField(verbose_name='numero de entradas')),
                ('discotecaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestas.discotecass')),
            ],
        ),
        migrations.CreateModel(
            name='Entradas',
            fields=[
                ('entradaId', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('N', 'Normal'), ('R', 'Reservado')], default='N', max_length=20)),
                ('coste', models.IntegerField(verbose_name='coste')),
                ('dni', models.CharField(max_length=9, verbose_name='dni')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('personas', models.IntegerField(verbose_name='personas')),
                ('fiestaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestas.fiestas')),
                ('usuarioId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestas.usuarios')),
            ],
        ),
    ]
