# Generated by Django 4.0.2 on 2023-01-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0007_discotecass_fiestas_entradas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='discotecaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestas.discotecass'),
        ),
    ]
