# Generated by Django 4.0.2 on 2023-01-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0008_usuarios_discotecaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha'),
        ),
    ]
