# Generated by Django 4.0.2 on 2023-01-30 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0009_entradas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='discotecaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestas.discotecass'),
        ),
    ]
