# Generated by Django 4.0.2 on 2023-02-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0010_entradas_discotecaid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discotecas',
        ),
    ]
