# Generated by Django 4.0.2 on 2023-02-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0011_delete_discotecas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discotecass',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='discotecass',
            name='descripciong',
            field=models.CharField(max_length=3000, null=True, verbose_name='descripcion grande'),
        ),
        migrations.AddField(
            model_name='discotecass',
            name='descripcionp',
            field=models.CharField(max_length=1500, null=True, verbose_name='descripcion pequeña'),
        ),
        migrations.AddField(
            model_name='discotecass',
            name='icono',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Icono'),
        ),
    ]
