# Generated by Django 4.0.2 on 2023-02-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0012_remove_discotecass_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discotecass',
            name='foto',
            field=models.ImageField(max_length=200, null=True, upload_to='imagenes/', verbose_name='Foto de Perfil'),
        ),
    ]
