# Generated by Django 4.0.2 on 2023-02-06 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0014_alter_discotecass_descripciong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('fotoId', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='fecha')),
                ('discotecaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestas.discotecass')),
            ],
        ),
    ]
