# Generated by Django 4.0.2 on 2023-02-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0015_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='fecha'),
        ),
    ]
