# Generated by Django 4.0.2 on 2023-02-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0016_alter_entradas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiestas',
            name='pagado',
            field=models.IntegerField(null=True, verbose_name='pagado'),
        ),
    ]
