# Generated by Django 4.0.2 on 2023-02-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0017_fiestas_pagado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiestas',
            name='pagado',
        ),
        migrations.AddField(
            model_name='entradas',
            name='pagado',
            field=models.IntegerField(null=True, verbose_name='pagado'),
        ),
    ]
