# Generated by Django 4.0.2 on 2023-02-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0018_remove_fiestas_pagado_entradas_pagado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('carritoId', models.AutoField(primary_key=True, serialize=False)),
                ('entradaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestas.entradas')),
                ('usuarioId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestas.usuarios')),
            ],
        ),
    ]
