# Generated by Django 4.0.2 on 2023-02-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0019_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='personas',
            field=models.IntegerField(null=True, verbose_name='personas'),
        ),
    ]
