# Generated by Django 4.0.2 on 2023-02-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0020_alter_entradas_personas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='entradaId',
        ),
        migrations.AddField(
            model_name='entradas',
            name='carritoId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiestas.carrito'),
        ),
    ]
