# Generated by Django 4.0.2 on 2023-02-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0021_remove_carrito_entradaid_entradas_carritoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='carritoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiestas.carrito'),
        ),
    ]
