# Generated by Django 4.0.2 on 2023-02-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0023_entradas_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='usuarioId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestas.usuarios'),
        ),
    ]
