# Generated by Django 4.0.2 on 2023-02-22 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0024_alter_entradas_usuarioid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscripciones',
            fields=[
                ('subscripcionId', models.AutoField(primary_key=True, serialize=False)),
                ('discotecaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestas.discotecass')),
                ('usuarioId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiestas.usuarios')),
            ],
        ),
    ]
