# Generated by Django 4.0.2 on 2023-03-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0025_subscripciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='correo_entrega',
            field=models.CharField(max_length=100, null=True, verbose_name='correo'),
        ),
    ]
