# Generated by Django 4.0.2 on 2023-03-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0028_rename_correo_entrega_entradas_correo_de_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Usuario'),
        ),
    ]
