# Generated by Django 4.0.2 on 2023-03-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0029_alter_usuarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='edad',
            field=models.IntegerField(null=True, verbose_name='edad'),
        ),
    ]
