# Generated by Django 4.0.2 on 2023-03-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0030_alter_usuarios_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.CharField(max_length=9, verbose_name='dni'),
        ),
    ]
