# Generated by Django 4.0.2 on 2023-05-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0031_alter_usuarios_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='edad',
            field=models.IntegerField(verbose_name='edad'),
        ),
    ]
