# Generated by Django 4.0.2 on 2023-05-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0033_alter_usuarios_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='edad',
            field=models.IntegerField(default='', max_length=3, verbose_name='edad'),
        ),
    ]
