# Generated by Django 4.0.2 on 2023-05-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0036_alter_usuarios_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(max_length=100, verbose_name='correo'),
        ),
    ]
