# Generated by Django 4.0.2 on 2023-05-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0037_alter_usuarios_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.CharField(default='', max_length=9, verbose_name='dni'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='edad',
            field=models.CharField(default='', max_length=3, verbose_name='edad'),
        ),
    ]
