# Generated by Django 4.0.2 on 2023-05-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0039_alter_usuarios_dni_alter_usuarios_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='dni',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='dni'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='edad',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='edad'),
        ),
    ]
