# Generated by Django 4.0.2 on 2023-05-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0041_alter_usuarios_dni_alter_usuarios_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(default='/imagenes/imagenes/30995.jpg', null=True, upload_to='imagenes/', verbose_name='Foto de Perfil'),
        ),
    ]
