# Generated by Django 4.0.2 on 2023-05-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0042_alter_usuarios_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(default='/media/imagenes/30995.jpg', null=True, upload_to='imagenes/', verbose_name='Foto de Perfil'),
        ),
    ]
