# Generated by Django 4.0.2 on 2023-06-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0043_alter_usuarios_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiestas',
            name='info_reservado',
            field=models.CharField(default='nada', max_length=1500, verbose_name='info del reservado'),
        ),
        migrations.AddField(
            model_name='fiestas',
            name='precio_reservado',
            field=models.IntegerField(default=100, verbose_name='precio del reservado'),
        ),
    ]
