# Generated by Django 4.0.2 on 2023-06-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiestas', '0044_fiestas_info_reservado_fiestas_precio_reservado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiestas',
            name='descripcion',
            field=models.TextField(max_length=1500, verbose_name='descripcion'),
        ),
    ]
